#' @title Insert Kronos Results into Metadata Tables.
#'
#' @description Build monthly time series objects using \cr\code{buildAchillesTs} on data generated by \cr\code{getAchillesData}
#'             and insert relevant time series analyses into metadata tables.
#'
#' @details This function will parse a data frame into time series objects, run analyses, then insert into metadata tables.
#'         The dataframe is assumed to come from \cr\code{getAchillesData} and have the correct structure.
#'
#' @usage  insertMetadata(achillesResultSet)
#'
#' @param connectionDetails An R object of type\cr\code{connectionDetails} created using the
#'                                     function \code{createConnectionDetails} in the
#'                                     \code{DatabaseConnector} package.
#' @param vocabDatabaseSchema             The schema that contains the OMOP vocab tables
#' @param resultsDatabaseSchema           The schema that contains the metadata table
#' @param rdsDir                           (Optional) a directory to store the results as RDS files
#'
#' @export
insertKronosMetadata <- function(connectionDetails, 
                                 vocabDatabaseSchema,
                                 resultsDatabaseSchema,
                                 rdsDir = NULL) {
  
  library(magrittr)
  
  achillesResultSet <- .getAchillesData(connectionDetails,
                                        vocabDatabaseSchema,
                                        resultsDatabaseSchema) %>%
    dplyr::filter(DOMAIN_ID != "Metadata" & DOMAIN_ID != "Visit" & CONCEPT_ID != 0)
  
  connection <- DatabaseConnector::connect(connectionDetails = connectionDetails)
  on.exit(DatabaseConnector::disconnect(connection = connection))
  
  metaAgentId <- .getKronosAgent(connectionDetails, resultsDatabaseSchema)
  
  # Parse the Achilles results and build time series objects
  
  for (entityConceptId in unique(achillesResultSet$CONCEPT_ID)) {
    AchillesTs   <- .buildAchillesTs(achillesResultSet[achillesResultSet$CONCEPT_ID == entityConceptId,])
    changePoints <- .getTrendChangePoints(AchillesTs[, "PREVALENCE"])
  
    if (nrow(changePoints) == 0) {
      next
    }
    dfs <- apply(X = changePoints, MARGIN = 1, function(k) {
      metaEntityActivityId <- .getMaxId("meta_entity_activity", "meta_entity_activity_id", connectionDetails, resultsDatabaseSchema)
      activityAsString  <- sprintf("Time series has a severity %s trend change point", k["SEVERITY"][[1]])
      df <- data.frame (
        meta_entity_activity_id = metaEntityActivityId,
        associated_entity_activity_id = NA,
        meta_agent_id = metaAgentId,
        entity_concept_id = entityConceptId,
        entity_as_string = NA,
        entity_identifier = NA,
        activity_concept_id       = 0,
        activity_type_concept_id  = 0,
        activity_as_string        = activityAsString,
        activity_start_date       = as.Date(k["DATES"][[1]]),
        activity_end_date         = NA,
        security_concept_id       = 0, 
        stringsAsFactors = FALSE
      )
      
      DatabaseConnector::insertTable(connection = connection, 
                                     tableName = sprintf("%s.meta_entity_activity", resultsDatabaseSchema),
                                     data = df, 
                                     dropTableIfExists = FALSE, 
                                     createTable = FALSE)
      
      df
    })
    
    if (!is.null(rdsDir)) {
      kronosResults <- do.call(rbind, dfs)
      if (!dir.exists(rdsDir)) {
        dir.create(path = rdsDir, recursive = TRUE)
      }
      saveRDS(object = kronosResults, file = file.path(rdsDir, sprintf("%d.rds", entityConceptId)))
    }
  }
}
